Contract:
  Bubble:
    visible: true
    localized_name:
      cn_zh: 泡影
      en: Bubble
    localized_description:
      cn_zh: 掉落物消失时间减少<!>%
      en: Item on the ground survive time -<!>%
    levelclass:
      - 1
      - 2
      - 3
    level0:
      - 30.0
      - 60.0
      - 90.0
  Burden:
    visible: true
    localized_name:
      cn_zh: 负重
      en: Burden
    localized_description:
      cn_zh: 背包格数每占用可用格子数量的1%，降低移速<!>%
      en: Every 1% occupied slot in available slots slow down your move speed by <!>%
    levelclass:
      - 1
      - 2
      - 3
    level0:
      - 0.5
      - 0.7
      - 0.9
  BurnOut:
    visible: true
    localized_name:
      cn_zh: 烈焰焚尽
      en: Burden
    localized_description:
      cn_zh: 烈焰人生命值提升<!>%，攻击力提升<!>%，攻速提高<!>%
      en: Blaze max health +<!>%, atk +<!>%, atk speed +<!>%
    levelclass:
      - 1
      - 2
    level0:
      - 100.0
      - 200.0
    level1:
      - 40.0
      - 80.0
    level2:
      - 100.0
      - 200.0
  CovertOperation:
    visible: true
    localized_name:
      cn_zh: 隐秘行动
      en: Covert Operation
    localized_description:
      cn_zh: 背包格子数量减少<!>%
      en: Available inventory slot -<!>%
    levelclass:
      - 1
      - 2
      - 3
    level0:
      - 25.0
      - 50.0
      - 75.0
  CreeperFusion:
    visible: true
    localized_name:
      cn_zh: 聚变
      en: Fusion
    localized_description:
      cn_zh: 所有Creeper的生命值提升<!>%,爆炸充能时间减少<!>%,爆炸范围提升<!>%
      en: Creeper max health +<!>%,charge time -<!>%,explode radius +<!>%
    levelclass:
      - 1
      - 2
      - 3
    level0:
      - 40.0
      - 80.0
      - 150.0
    level1:
      - 0.0
      - 40.0
      - 80.0
    level2:
      - 50.0
      - 100.0
      - 200.0
  DeathLimit:
    visible: true
    localized_name:
      cn_zh: 战术容错
      en: Death Limit
    localized_description:
      cn_zh: 全局共享开局人数 x <!>的再部署次数， 无等级则为30.
      en: All players share number of players multiply <!> times of re-deploy. 60 by default.
    levelclass:
      - 2
      - 4
      - 6
    level0:
      - 20.0
      - 10.0
      - 5.0
  EnderLord:
    visible: true
    localized_name:
      cn_zh: 领主
      en: EnderLord
    localized_description:
      cn_zh: 末影龙生命值提升<!>%，攻击力提升<!>%，免疫爆炸伤害
      en: Ender Dragon Max HP +<!>%, ATK +<!>%, immune explode damage.
    levelclass:
      - 1
      - 2
      - 3
    level0:
      - 100.0
      - 200.0
      - 300.0
    level1:
      - 50.0
      - 100.0
      - 200.0
  Erode:
    visible: true
    localized_name:
      cn_zh: 侵蚀
      en: Erode
    localized_description:
      cn_zh: 所有玩家的生命上限降低<!>%
      en: Player's max health decrease <!>%
    levelclass:
      - 1
      - 2
      - 3
      - 4
    level0:
      - 30.0
      - 50.0
      - 70.0
      - 90.0
  Eutrophic:
    visible: true
    localized_name:
      cn_zh: 富营养
      en: Erode
    localized_description:
      cn_zh: 水生生物有<!>%概率变为守卫者
      en: Water life <!>% chance turned into guardian
    levelclass:
      - 2
    level0:
      - 25.0
  ForeverNight:
    visible: true
    localized_name:
      cn_zh: 永夜
      en: Forever Night
    localized_description:
      cn_zh: 永远是夜晚
      en: Night Forever
    levelclass:
      - 2
    level0:
      - 0.0
  FireObsessed:
    visible: true
    localized_name:
      cn_zh: 火之骄子
      en: Fire Obsessed
    localized_description:
      cn_zh: 所有玩家的燃烧时间延长<!>%
      en: Player's burn time extend <!>%
    levelclass:
      - 1
      - 2
    level0:
      - 200.0
      - 1000.0
  FromEnd:
    visible: true
    localized_name:
      cn_zh: 来自终末
      en: From End
    localized_description:
      cn_zh: 末影人的生命提升<!>%，攻击力提升<!>%，自带<!>点护甲
      en: Enderman max health +<!>%, atk +<!>%, has <!> shield point
    levelclass:
      - 1
      - 2
    level0:
      - 75.0
      - 200.0
    level1:
      - 25.0
      - 60.0
    level2:
      - 5.0
      - 12.0
  HeavyShield:
    visible: true
    localized_name:
      cn_zh: 重盾
      en: Heavy Shield
    localized_description:
      cn_zh: 以盾牌阻挡潜在伤害后冷却<!>秒
      en: Shield cool down <!>s after void damage
    levelclass:
      - 1
      - 2
    level0:
      - 30.0
      - 120.0
  HematopoieticDisorders:
    visible: true
    localized_name:
      cn_zh: 造血障碍
      en: Hematopoietic Disorders
    localized_description:
      cn_zh: 玩家生命回复减少<!>%
      en: Player heal effect -<!>%
    levelclass:
      - 1
      - 2
    level0:
      - 40.0
      - 80.0
  HighValueTarget:
    visible: true
    localized_name:
      cn_zh: 高价值目标
      en: High Value Target
    localized_description:
      cn_zh: 所有我方单位的攻击力降低<!>%
      en: Friendly Unit atk -<!>%
    levelclass:
      - 1
      - 2
    level0:
      - 30.0
      - 60.0
  Insomnia:
    visible: true
    localized_name:
      cn_zh: 失眠
      en: Insomnia
    localized_description:
      cn_zh: 无法跳过夜晚
      en: Unable skip night
    levelclass:
      - 1
    level0:
      - 0.0
  LongLifeArmy:
    visible: true
    localized_name:
      cn_zh: 长生军
      en: Long Life Army
    localized_description:
      cn_zh: 僵尸的生命提升<!>%，生成时额外生成<!>只僵尸
      en: Zombie's max health +<!>%, spawn <!> more zombies
    levelclass:
      - 1
      - 2
    level0:
      - 40.0
      - 100.0
    level1:
      - 4
      - 6
  MechanicalDisaster:
    visible: true
    localized_name:
      cn_zh: 机械之灾
      en: MechanicalDisaster
    localized_description:
      cn_zh: 活塞不再响应红石信号
      en: Pistons no longer respond to redstone signal
    levelclass:
      - 1
    level0:
      - 0.0
  MineralPaucity:
    visible: true
    localized_name:
      cn_zh: 矿物贫乏
      en: Mineral Paucity
    localized_description:
      cn_zh: 矿物挖掘后有<!>%概率无掉落物
      en: <!>% chance get nothing after mine a mineral
    levelclass:
      - 1
      - 2
    level0:
      - 30.0
      - 75.0
  NoFish:
    visible: true
    localized_name:
      cn_zh: 海之嫌弃
      en: No Fish
    localized_description:
      cn_zh: 海不回应，但你仍能学到些什么
      en: The sea respond nothing, but you still learn from it.
    levelclass:
      - 1
    level0:
      - 0.0
  Octane:
    visible: true
    localized_name:
      cn_zh: 辛烷
      en: Octane
    localized_description:
      cn_zh: 敌对生物移速增加<!>%
      en: Mob's move speed +<!>%
    levelclass:
      - 1
      - 2
      - 3
    level0:
      - 30.0
      - 60.0
      - 100.0
  OnFire:
    visible: true
    localized_name:
      cn_zh: 易燃
      en: OnFire
    localized_description:
      cn_zh: <!>格内的高温源使你着火，包括身上的岩浆桶
      en: You are easily catch fire
    levelclass:
      - 1
      - 2
    level0:
      - 2.0
      - 4.0
  Pneumonia:
    visible: true
    localized_name:
      cn_zh: 肺炎
      en: Pneumonia
    localized_description:
      cn_zh: 肺活量减少<!>%
      en: Max Air -<!>%
    levelclass:
      - 1
      - 2
    level0:
      - 50.0
      - 90.0
  PoorTools:
    visible: true
    localized_name:
      cn_zh: 拙劣
      en: PoorTools
    localized_description:
      cn_zh: 工具/装备损坏加快<!>%
      en: Tools/Equipments damage +<!>%
    levelclass:
      - 1
      - 2
    level0:
      - 100.0
      - 300.0
  ShareDamage:
    visible: true
    localized_name:
      cn_zh: 血脉相连
      en: MechanicalDisaster
    localized_description:
      cn_zh: 当有玩家受伤时，其他玩家受到该次伤害<!>%的生命流失
      en: When a player damaged, other players loss <!>% life of this damage
    levelclass:
      - 1
      - 2
    level0:
      - 30.0
      - 60.0
  SharpArrow:
    visible: true
    localized_name:
      cn_zh: 锐箭
      en: Sharp Arrow
    localized_description:
      cn_zh: 骷髅的移动速度提升<!>，弓箭伤害提升<!>%且火焰附加
      en: Skeleton's speed +<!>%,arrow damage +<!>% and set fire
    levelclass:
      - 1
      - 2
    level0:
      - 30.0
      - 50.0
    level1:
      - 50.0
      - 125.0
  Silence:
    visible: true
    localized_name:
      cn_zh: 大静谧
      en: Silence
    localized_description:
      cn_zh: 只有<!>格内的玩家可以与你聊天
      en: Only players with in <!> blocks can chat with you
    levelclass:
      - 1
      - 2
    level0:
      - 64.0
      - 24.0
  Stimulation:
    visible: true
    localized_name:
      cn_zh: 刺激
      en: Stimulation
    localized_description:
      cn_zh: 所有敌人的攻击力提升<!>%
      en: All enemy's atk +<!>%
    levelclass:
      - 1
      - 2
      - 3
    level0:
      - 40.0
      - 90.0
      - 150.0
  Tasteless:
    visible: true
    localized_name:
      cn_zh: 食之无味
      en: Tasteless
    localized_description:
      cn_zh: 饥饿值损失加快<!>%
      en: Hunger bar loss <!>% faster
    levelclass:
      - 1
      - 2
    level0:
      - 100.0
      - 200.0
  ThickMob:
    visible: true
    localized_name:
      cn_zh: 活性
      en: Thick Mob
    localized_description:
      cn_zh: 所有敌对生物的生命值提升<!>%
      en: All enemy's max health +<!>%
    levelclass:
      - 1
      - 2
      - 3
    level0:
      - 50.0
      - 100.0
      - 200.0
  WhiteTerror:
    visible: true
    localized_name:
      cn_zh: 白色恐怖
      en: White Terror
    localized_description:
      cn_zh: 恶魂的生命值+<!>%，移动速度+<!>%
      en: Ghast's max health +<!>%, move speed +<!>%
    levelclass:
      - 1
    level0:
      - 200.0
    level1:
      - 400.0
  ZombiePiglinAnger:
    visible: true
    localized_name:
      cn_zh: 猪灵敌意
      en: ZombiePiglinAnger
    localized_description:
      cn_zh: 僵尸猪人憎恨你
      en: Zombie piglin hate You
    levelclass:
      - 1
    level0:
      - 0.0
Information:
  GameStart:
    cn_zh: 开始了游戏
    en: GameStart
  GameHadStarted:
    cn_zh: 游戏已经开始了
    en: GameHadStarted
  GameStop:
    cn_zh: 合约已中止
    en: GameFinished
  gameHadStopped:
    cn_zh: 游戏未在进行
    en: GameIsAlreadyOff
  GameIsRunning:
    cn_zh: 游戏正在进行
    en: GameIsRunning
  GameWaitReset:
    cn_zh: 游戏准备重置
    en: GameIsWaitingForReset
  ContractLocked:
    cn_zh: 合约已锁定
    en: ContractLocked
  ShouldSendMessageAsPlayer:
    cn_zh: 必须以玩家身份使用该命令。
    en: Must send command as player.
  IndexOutOfBoundary:
    cn_zh: 参数范围超限。
    en: Argument out of range.
  NotEnoughArguments:
    cn_zh: 命令参数不足。
    en: Not enough arguments.
  TooManyArguments:
    cn_zh: 命令参数过多。
    en: Too many arguments.
  ChangingAnInvisibleContract:
    cn_zh: 更改一个不可见的合约。
    en: You are not HarryPotter.
  WrongArgumentType:
    cn_zh: 错误的参数类型。
    en: Wrong argument type.
  PickUpABubble:
    cn_zh: 你捡起了/个/的泡影，该物品在/秒之前已经消失
    en: You picked up / bubbles of /, disappeared / seconds ago
  TotalContractLevel:
    cn_zh: 总合约等级
    en: Total Contract Level
  StartPlayerJoinVote:
    cn_zh: 想要加入游戏
    en: want to join
  StartPlayerJoinVoteButton:
    cn_zh: 赞同加入
    en: Agree Join
  StartGameStopVote:
    cn_zh: 发起了停止合约投票
    en: start a vote to stop contract
  StartGameResetVote:
    cn_zh: 发起了地图重置投票
    en: start a vote to reset map
  StartGameStopVoteButton:
    cn_zh: 点此同意
    en: Click Here to Agree
  StartGameResetVoteButton:
    cn_zh: 点此同意
    en: Click Here to Agree
  AVoteIsRunning:
    cn_zh: 有一项投票正在进行
    en: A STOP CONTRACT vote is already running
  VoteNotEnough:
    cn_zh: 投票人数不足
    en: Not Enough Vote
  VoterNotSurvival:
    cn_zh: 投票者非生存模式
    en: Voter not SURVIVAL
  voterNotSurvivalOrAdventure:
    cn_zh: 投票者非生存模式或冒险模式
    en: Voter not SURVIVAL or ADVENTURE
  VoteSuccess:
    cn_zh: 投票成功
    en: Vote Successful
  NoVoteIsRunning:
    cn_zh: 没有投票正在进行
  VoteCreatorNotSurvival:
    cn_zh: 创建投票者非生存模式
    en: Vote Creator not SURVIVAL
  voteCreatorNotSurvivalOrAdventure:
    cn_zh: 创建投票者非生存模式或冒险模式
    en: Vote Creator not SURVIVAL or ADVENTURE
  NoVoteForSelf:
    cn_zh: 不可为自己投票
    en: No Self Vote
  NoStartAFailedGame:
    cn_zh: 请重置已经失败的游戏
    en: Please reset a FAILED game
Position:
  PlayerJoin:
    world: world_lobby
    spawn_point_override: false
  OverWorld:
    world: world
    spawn_point_override: false
  Nether:
    world: world_nether
    spawn_point_override: false
  End:
    world: world_the_end
    spawn_point_override: false
WorldGenerate:
  LoadWorld:
    - world
    - world_the_end
    - world_nether
    - world_lobby
  GenerateArguments:
    world_lobby:

Vote:
  Ratio:
    stop: 0.5
    reset: 0.5
    join: 0.5
  Time:
    stop: 15
    reset: 15
    join: 15
Status:
  Name:
    cn_zh: 数据
    en: Stats
General:
  Language: cn_zh